#!/bin/sh /etc/rc.common
# Fuck Gfw to   shadowsocks or sock5 proxy
# Copyright (C) 2007 OpenWrt.org

START=96
STOP=96

IPTABLES="/usr/sbin/iptables"

SS_HOST="127.0.0.1"
SS_PORT="1080"
NAT_CN="SHADOWSOCKSNAT"

start() {
        ${IPTABLES} -t nat -N ${NAT_CN}
        ${IPTABLES} -t nat -A ${NAT_CN} -d ${SS_HOST} -j RETURN
        ${IPTABLES} -t nat -A ${NAT_CN} -p tcp -j REDIRECT --to-ports ${SS_PORT}
        ${IPTABLES} -t nat -I PREROUTING -s 10.168.0.1/24 -m set --match-set vpn dst -j ${NAT_CN}
        echo ">> init table shadowsocks nat ok."
}

stop() {
        ${IPTABLES} -t nat -D PREROUTING -s 10.168.0.1/24 -m set --match-set vpn dst -j ${NAT_CN}
        ${IPTABLES} -t nat -F ${NAT_CN}
        ${IPTABLES} -t nat -X ${NAT_CN}
        echo ">> remove table shadowsocks nat ok."
}
