#!/bin/sh
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"

if [ "$1" != "pptp-vpn" ]; then
    exit 0                   
fi

OLDGW=`cat /tmp/vpn_oldgw`
route add default gw $OLDGW

route del -net 1.0.0.0 netmask 255.0.0.0
route del -net 14.0.0.0 netmask 255.0.0.0
route del -net 27.0.0.0 netmask 255.0.0.0
route del -net 36.0.0.0 netmask 255.0.0.0
route del -net 39.0.0.0 netmask 255.0.0.0
route del -net 42.0.0.0 netmask 255.0.0.0
route del -net 49.0.0.0 netmask 255.0.0.0
route del -net 58.0.0.0 netmask 255.0.0.0
route del -net 59.0.0.0 netmask 255.0.0.0
route del -net 60.0.0.0 netmask 255.0.0.0
route del -net 61.0.0.0 netmask 255.0.0.0
route del -net 101.0.0.0 netmask 255.0.0.0
route del -net 103.0.0.0 netmask 255.0.0.0
route del -net 106.0.0.0 netmask 255.0.0.0
route del -net 110.0.0.0 netmask 255.0.0.0
route del -net 111.0.0.0 netmask 255.0.0.0
route del -net 112.0.0.0 netmask 255.0.0.0
route del -net 113.0.0.0 netmask 255.0.0.0
route del -net 114.0.0.0 netmask 255.0.0.0
route del -net 115.0.0.0 netmask 255.0.0.0
route del -net 116.0.0.0 netmask 255.0.0.0
route del -net 117.0.0.0 netmask 255.0.0.0
route del -net 118.0.0.0 netmask 255.0.0.0
route del -net 119.0.0.0 netmask 255.0.0.0
route del -net 120.0.0.0 netmask 255.0.0.0
route del -net 121.0.0.0 netmask 255.0.0.0
route del -net 122.0.0.0 netmask 255.0.0.0
route del -net 123.0.0.0 netmask 255.0.0.0
route del -net 124.0.0.0 netmask 255.0.0.0
route del -net 125.0.0.0 netmask 255.0.0.0
route del -net 126.0.0.0 netmask 255.0.0.0
route del -net 169.0.0.0 netmask 255.0.0.0
route del -net 175.0.0.0 netmask 255.0.0.0
route del -net 180.0.0.0 netmask 255.0.0.0
route del -net 182.0.0.0 netmask 255.0.0.0
route del -net 183.0.0.0 netmask 255.0.0.0
route del -net 202.0.0.0 netmask 255.0.0.0
route del -net 203.0.0.0 netmask 255.0.0.0
route del -net 210.0.0.0 netmask 255.0.0.0
route del -net 211.0.0.0 netmask 255.0.0.0
route del -net 218.0.0.0 netmask 255.0.0.0
route del -net 219.0.0.0 netmask 255.0.0.0
route del -net 220.0.0.0 netmask 255.0.0.0
route del -net 221.0.0.0 netmask 255.0.0.0
route del -net 222.0.0.0 netmask 255.0.0.0
route del -net 223.0.0.0 netmask 255.0.0.0
rm /tmp/vpn_oldgw

ROUTE_DEFAULT=`route | grep default`
if [ "$ROUTE_DEFAULT" == "" ]; then
  OLDGW=`route  | grep eth0 | grep -v '*' | awk '{print $2}'`
  route add default gw $OLDGW
fi

