#!/bin/sh
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"

if [ "$1" != "pptp-vpn" ]; then
    exit 0
fi

OLDGW=`ip route show | grep '^default' | sed -e 's/default via \([^ ]*\).*/\1/'`

if [ $OLDGW == '' ]; then
    exit 0
fi

if [ ! -e /tmp/vpn_oldgw ]; then
    echo $OLDGW > /tmp/vpn_oldgw
fi

for x in `cat /etc/ppp/outip.txt`; do
    route add -net $x netmask 255.0.0.0 gw $OLDGW
done

